#
# This is a project Makefile. It is assumed the directory this Makefile resides in is a
# project subdirectory.
#

PROJECT_NAME := mqtt_no_ssl

EXTRA_COMPONENT_DIRS += ./portMQTT
		
include $(IDF_PATH)/make/project.mk

